import { 
  Box,
  Container,
  Heading,
  Text
} from "@chakra-ui/react";

export function Pccompany () {
  return(
    <Box>
      <Container
        maxW='container.lg'
        display='flex'
        my='10'
      >
        <Text
          fontWeight='bold'
          whiteSpace='nowrap'
        >
          特定商取引法に基づく記載
        </Text>
        <Box
          mx='10'
        >
          <Box>
            <Text
              fontWeight='bold'
            >
              販売事業者
            </Text>
            <Text>
              株式会社ミューズ・ラ・ムー
            </Text>
          </Box>
          <Box>
            <Text
              fontWeight='bold'
              mt='8'
            >
              運営統括責任者
            </Text>
            <Text>
              代表取締役　矢代修子
            </Text>
          </Box>
          <Box>
            <Text
              fontWeight='bold'
              mt='8'
            >
              所在地
            </Text>
            <Text>
              〒530-0001 <br />
              大阪府大阪市北区梅田1-11-4  大阪駅前第4ビル1F24
            </Text>
          </Box>
          <Box>
            <Text
              fontWeight='bold'
              mt='8'
            >
              電話番号
            </Text>
            <Text>
              06-6344-7603
            </Text>
          </Box>
          <Box>
            <Text
              fontWeight='bold'
              mt='8'
            >
              e-mail
            </Text>
            <Text>
              museslamu@miracle.ocn.ne.jp
            </Text>
          </Box>
          <Box>
            <Text
              fontWeight='bold'
              mt='8'
            >
              ホームページ
            </Text>
            <Text>
              museslamu.art
            </Text>
          </Box>
          <Box>
            <Text
              fontWeight='bold'
              mt='8'
            >
              美術品商許可番号
            </Text>
            <Text>
              大阪府公安委員会許可第621016200105号
            </Text>
          </Box>
        </Box>
      </Container>
    </Box>
  )
}