import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Box } from '@chakra-ui/react'
import { Header } from '../components/global/header'
import { Hero } from '../components/home/hero'
import { About } from '../components/home/about'
import { Gallery } from '../components/home/gallery'
import { Footer } from '../components/global/footer'
import { Sphero } from '../components/sp/spHero'
import { Spabout } from '../components/sp/spAbout'
import { Spgallery } from '../components/sp/spGallery'
import { Spfooter } from '../components/global/spFooter'
import { Spcontact } from '../components/sp/spConatct'

export default function Home() {
  return (
    <Box className={styles.container}>
      
      <Head>
        <title>大阪梅田 | ギャラリーら・む〜</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Box className={styles.pc}>

        <Header />

        <Hero className={styles.contents}/>

        <About className={styles.contents}/>

        <Gallery  className={styles.contents}/>

        <Footer />

      </Box>

      <Box className={styles.sp}>

        <Header />

        <Sphero />

        <Spabout />

        <Spgallery />

        <Spcontact />

        <Spfooter />
      
      </Box>

    </Box>
  )
}
