import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Box } from '@chakra-ui/react'
import { Menubar } from '../components/global/menuBar'
import { Spfooter } from '../components/global/spFooter'
import { Hero } from '../components/home/hero'
import { Exhibition } from '../components/home/exhibitions'
import { Contact } from '../components/home/contact'
import { Pchero } from '../components/home/pcHero'

export default function Home() {
  return (
    <Box className={styles.container}>
      
      <Head>
        <title>大阪梅田 | ギャラリーら・む〜</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Box className={styles.pc}>

        <Menubar />

        <Pchero />

        <Exhibition />

        <Contact />

        <Spfooter />

      </Box>

      <Box className={styles.sp}>

        <Menubar />

        <Hero />

        <Exhibition />

        <Contact />

        <Spfooter />
      
      </Box>

    </Box>
  )
}
